# Generated by Django 2.1.5 on 2019-01-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_model',
            name='status',
            field=models.CharField(blank='true', max_length=2),
        ),
    ]
