# Generated by Django 2.1.5 on 2019-01-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190125_1248'),
        ('dashboard', '0005_addcards'),
    ]

    operations = [
    ]
