# Generated by Django 2.1.5 on 2019-01-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_merge_20190129_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcards',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='addcards',
            name='file',
            field=models.FileField(upload_to='uploads/jsfiles/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='addcards',
            name='image',
            field=models.ImageField(upload_to='uploads/image/%Y/%m/%d'),
        ),
    ]
