# Generated by Django 2.1.5 on 2019-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190131_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='createdVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.FileField(upload_to='')),
                ('user_rel', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='addcards',
            name='audio',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/audiofiles'),
        ),
        migrations.AlterField(
            model_name='addcards',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/jsfiles'),
        ),
        migrations.AlterField(
            model_name='addcards',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/image'),
        ),
    ]
